### ISSUE TITLE
Anlagensteuerung

### ISSUE THREAD

**Issue by ReneHerthel** [ReneHerthel/ConveyorBelt#19]
* Ablaufsteuerung über beide Förderbänder implementiert (ohne Ausnahmebehandlung)
* Testablauf mit allen Bauteilen arbeitet fehlerfrei und ist dokumentiert

* Implementation der verarbeitenden Schicht
* Test Funktionsfähigkeit, ein Förderband
* Entwurf der Kommunikation zwischen den beiden Förderbändern

**Comment by ReneHerthel** [comment]
https://github.com/ReneHerthel/ConveyorBelt/issues/21

**Comment by Siltyx** [comment]
Hier fehlt nur noch die rampe
