### ISSUE TITLE
Code Smells in HAL

### ISSUE THREAD

**Issue by Joniboniboo** [ReneHerthel/ConveyorBelt#2]
@ReneHerthel bitte korrigieren:
1. Einrückung
2. Default-Konstruktoren entfernen
3. Kommentar bitte auf Englisch
4. Methodennamen fangen IMMER mit einem Kleinbuchstaben an

**Comment by ReneHerthel** [comment]
@Joniboniboo 
1. Welche Einrückungen meinst du?
3. Welche Kommentare meinst du?

**Comment by ReneHerthel** [comment]
Close, weil alle daran weiterarbeiten
