### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by ReneHerthel** [ReneHerthel/ConveyorBelt#20]
* Timerklasse für zeitgesteuert Ausnahmebehandlung implementiert
* Timingverhalten bezüglich HW- und BS-Timer im RDD diskutiert

**Comment by ReneHerthel** [comment]
@Joniboniboo Gehört das zu dem Timer den du implementiert hast?

**Comment by Joniboniboo** [comment]
Schon irgendwo. In dem Sinne ist das aber abgehakt. Außer da ist noch Redebedarf.

**Comment by ReneHerthel** [comment]
Da es seit längerer Zeit als abgehakt gilt und kein Redebedarf mehr vorhanden war, wird es geschlossen.
