### ISSUE TITLE
Merge conflict commments

### ISSUE THREAD

**Issue by ReneHerthel** [ReneHerthel/ConveyorBelt#27]
@thismath @Joniboniboo  @Siltyx 
Bitte im ``/src/Timer/ITimer.h`` die Git-Konfilkt Kommentare entfernen und woanders auch falls vorhanden, Danke.

**Comment by ReneHerthel** [comment]
/src/Timer/IDistanceTracker.h

**Comment by ReneHerthel** [comment]
/src/Timer/TimerService.h

**Comment by ReneHerthel** [comment]
/src/Timer/TimerService.cpp

**Comment by ReneHerthel** [comment]
Habe ich was übersehen?

**Comment by ReneHerthel** [comment]
/src/examples/PulseMessage/ThreadClient.cpp

**Comment by ReneHerthel** [comment]
Irgendwer hat unsauber gepusht

**Comment by thismath** [comment]
müsste alle erwischt haben
