### ISSUE TITLE
testclass für ILightsystem   

### ISSUE THREAD

**Issue by thismath** [ReneHerthel/ConveyorBelt#37]
setWarning level verwenden
extra: im thread
Vorhandene Klassen auf TestFrameWork portieren

**Comment by thismath** [comment]
Geschätzte Arbeitszeit: 1 Tag

**Comment by ReneHerthel** [comment]
@thismath Ist das hier fertig?

**Comment by thismath** [comment]
tatsächlicher Zeitaufwand: 1 Tag
