### ISSUE TITLE
Testkonzepte für die Abnahme

### ISSUE THREAD

**Issue by ReneHerthel** [ReneHerthel/ConveyorBelt#4]

**Comment by ReneHerthel** [comment]
@thismath @Siltyx @Joniboniboo @abt674 @snje Gab es hier noch etwas zu besprechen oder kann es geschlossen werden?

**Comment by Siltyx** [comment]
Nicht wirklich, das ist nicht benutzbar

**Comment by ReneHerthel** [comment]
Dann müssen wir da nochmal ran.
