### ISSUE TITLE
ISR Example

### ISSUE THREAD

**Issue by ReneHerthel** [ReneHerthel/ConveyorBelt#52]
Das hier `#include "ConveyorBelt-devel/src/HWaccess.h"` in dieser [Datei](https://github.com/ReneHerthel/ConveyorBelt/blob/devel/src/examples/ISR/isr_pulse.cpp) sieht für mich etwas merkwürdig aus.
Wenn das auf dem Devel gemerged wird, müsste das auch ohne `ConveyorBelt-devel` gehen oder?

Bei gelegenheit vlt fixen :-)

**Comment by ReneHerthel** [comment]
@abt674 Eine kleine Idee, die nützlich für alle sein könnte:
Da du dich meines Wissens nach als einziger mit der ISR beschäftigt hast, könntest du vielleicht im Example-Code kommentieren, wofür die ganzen Hardcoded-values stehen, die du den Funktionen übergibts?
Wäre cool in Erfahrung zu bringen, damit wir vielleicht besser verstehen, was diese bedeuten, wenn wir alle anfangen sollten ISR's zu nutzen :-).

**Comment by Siltyx** [comment]
Die Hardcoded Values stehen für bestimmte ISR Steuerung in den IO Bausteinen, deswegen können wir auch nicht InterruptAttachEvent benutzen, die ISR müssen wir selber schreiben, die muss nähmlich den Interrupt im IO Baustein maskieren, das kann das OS natürlich nicht.

**Comment by ReneHerthel** [comment]
@Siltyx Danke, das ist schon mal ein Anfang.
