### ISSUE TITLE
Betriebssystem Kapseln

### ISSUE THREAD

**Issue by Siltyx** [ReneHerthel/ConveyorBelt#53]
Ich denke das eine Kapselung von OS spezifischen Operationen Sinnvoll wäre (und sie evtl. auch eingefordert werden wird), besonders um auch zuhause Sinnvoll entwickeln und Testen zu können. Meinungen?

**Comment by ReneHerthel** [comment]
Ist hierzu etwas passiert?

**Comment by thismath** [comment]
ist dafür nicht der pulsemessage wrapper instantiiert worden?

**Comment by ReneHerthel** [comment]
@thismath Der PulseMessageWrapper ist wahrscheinlich nicht die einzige OS spezifische Kapselung.
Besser gefragt: Gibt es noch andere Meinungen oder Ideen, oder kann das geschlossen werden?

**Comment by Joniboniboo** [comment]
Also der timer ist in dem Sinne auch eine BS Kapselung. Das wäre aber auch abgeschlossen. Die "Interrupts" laufen ja auch übers BS. Hab ich was vergessen? Andernfalls im Meeting nochmal ansprechen.
