### ISSUE TITLE
Vorhandene main methoden entfernen

### ISSUE THREAD

**Issue by Siltyx** [ReneHerthel/ConveyorBelt#55]

**Comment by ReneHerthel** [comment]
Im devel branch:

- [ ] @ReneHerthel @Joniboniboo ConveyorBelt/src/examples/HeightMeasurement/Main.cpp
- [ ] @Joniboniboo ConveyorBelt/src/examples/Logger/Main.cpp
- [ ] @Siltyx (?) ConveyorBelt/src/examples/PulseMessage/Main.cpp
- [ ] @ReneHerthel ConveyorBelt/src/examples/PulseMessageWrapper/Main.cpp

**Comment by Siltyx** [comment]
Jo ich entferne demnächst die main aus den **examples** und tu die einfach in einen Testcase
