### ISSUE TITLE
Implementierung: Wait, Resume, Pulse Message nach außen, Mess Thread blockierung, Idle State nach Invalid und Unexpexted

### ISSUE THREAD

**Issue by Joniboniboo** [ReneHerthel/ConveyorBelt#57]

**Comment by ReneHerthel** [comment]
[X] Idle State nach INvalid und Unexpected
[ ] Wait
[ ] Resume
[ ] Pulse messagae nach außen
[ ] Mess thread blockierung

**Comment by ReneHerthel** [comment]
@Joniboniboo Da wir gesagt haben, dass das "Wait", "Resume" und "Mess thread blockierung" nicht mehr benötigt wird, kann dieser Issue geschlossen werden
