### ISSUE TITLE
ConveyorBelt Rightslow is not working

### ISSUE THREAD

**Issue by abt674** [ReneHerthel/ConveyorBelt#59]

**Comment by ReneHerthel** [comment]
Hab jetzt vodefinierte Werte aus der HWdefines.h genommen. und den Methodennamen geändert.

**Comment by ReneHerthel** [comment]
Ist es jetzt gefixt?

**Comment by ReneHerthel** [comment]
@abt674 ping.

**Comment by ReneHerthel** [comment]
@abt674 Hat sich dieser Issue erledigt?

**Comment by abt674** [comment]
Für mich hat sich das erledigt, da die ISR nicht das Band steuert. Das Problem war/ist das der Aufruf: service.ConveyorBeltChangeState(RIGHTSLOW) das Band stoppt. Als ich den Aufruf durch: out8(0x300, (in8(0x300) | 1 << (0 | 2))); ersetzt habe, hat es funktioniert.

**Comment by ReneHerthel** [comment]
@abt674 Also muss da nichts mehr gefixt werden, wenn ich das richtig verstehe?

**Comment by abt674** [comment]
So ist es
