### ISSUE TITLE
Locking für I/O-Ports

### ISSUE THREAD

**Issue by snje** [ReneHerthel/ConveyorBelt#61]
Nichtatomare Lese-Schreib-Zyklen müssen geschützt werden. QNX Weg siehe @cyrildzumts.

Geschätzte Zeit: 1h
Benötigte Zeit:

**Comment by ReneHerthel** [comment]
@snje Was ist davon alles betroffen? Die gesamte Aktorik/Sensorik (bzw. HAL)? Auf welchen Code wird verwiesen?

**Comment by snje** [comment]
Alle IO-Ports auf die mehrere Threads gleichzeitig schreiben und/oder lesen können. Am Elegantesten wäre die Kapselung der jeweiligen Ports in einzelne Objekte um jedem Port einen eigenen Mutex zuzuordnen. Beispielcode gibt's in der [Thread Synchronisations Demo](https://gist.github.com/cyrildzumts/d2095385b0ef156aaf1afed2b6d06e0c) bei @cyrildzumts.

**Comment by snje** [comment]
Bitte dem Singleton auch die Portkonfiguration beim Instantiieren überlassen.
`out8(CTRL_REG_GROUP0, DEFAULT_PORTS_SETTINGS);`

**Comment by ReneHerthel** [comment]
@snje Hab ich ungetested eingefügt.
