### ISSUE TITLE
Pulse Wrapper kann keine Codes schicken

### ISSUE THREAD

**Issue by Siltyx** [ReneHerthel/ConveyorBelt#64]
Der PM Wrapper kann nur values verschicken, keine Codes. Bitte fixen. 
EDIT: Gilt beim empfangen genauso

Evtl struct sinnvoll mit code und value???

**Comment by ReneHerthel** [comment]
@Siltyx Was meinst du genau mit Codes? Das Bit-Code-Pattern der Werkstücke?

**Comment by Siltyx** [comment]
Genau, eine Pulse msg transportiert 40Bit daten, 32Bit Value und den 8Bit code, denn code brauchen wir auch noch. Ich glaube das Struct  wäre eine gute Lösung, dann zwei methoden

´´´c++
int sendPulseMessage(int8_t code, int32_t value);
int sendPulseMessage(struct pulse p);
´´´

**Comment by ReneHerthel** [comment]
@Siltyx Okey. Ich habe ein Fix gepusht. Allerdings untested. Kannst du ja, wenn du magst bei gelegenheit ausprobieren :-)

**Comment by Siltyx** [comment]
Test geupdated? Dann kann ich das laufen lassen wenn ich das nächste mal im lab bin

**Comment by ReneHerthel** [comment]
@Siltyx Den Test hab ich auch abgeändert, ja.

**Comment by Siltyx** [comment]
Super :)

**Comment by ReneHerthel** [comment]
@Siltyx Schon ausprobiert?

**Comment by ReneHerthel** [comment]
Sollte gefixt sein.
