### ISSUE TITLE
Implementation des "Embedded Recorder"

### ISSUE THREAD

**Issue by ReneHerthel** [ReneHerthel/ConveyorBelt#65]
Folgende Punkte werden für die Requirements benötigt:
- [x] ~Use Case diagram~
- [x] Sequence diagram
- [x] ~Component diagram~
- [x] ~Activity diagram~
- [x] Class diagram
- [x] Speichert folgende Informationen der Lichtschranken, Druckknöpfe, Serielle Schnittstellen, Mess-Sensorik & Menü-Steuerung
  - Signaltyp
  - Zeitpunkt in ms
  - Sowie u.U. Messwerte, Nachrichten, oder Eingabewerte.
  - ( EDIT: Bei uns: Time, Code, Value)
- [x] ~Dimensionierung der Speicherkapazität, so das mindestens 30 Sekunden Länge (Auch unter Vollast) aufgezeichnet werden können~
- [x] ~Ringbuffer um fortlaufend Signale und Nachrichten abzuspeichern~
- [x] Feature: PlayRecordedData (Einspeisung gespeicherter Signale in die Software)
- [x] Feature: ShowRecordedData (Gespeicherte Daten in geeigneter Weise visualisieren)
- [x] Feature: SaveRecordedData (Abspeichern der Daten in geeigneter Weise)
- [x] Feature: LoadRecordedData (Wiederverwendung der Daten in geeigneter Weise)
- [x] Test successfully
Änderungen:
 - [x] Der Ringbuffer fällt weg.
 - [x] Show Recorded data schreibt den Buffer in eine Text datei
 - [x] Senden von Pulse messages in den richtigen Zeitabständen

Änderungen:
 - [x] Speichere den Puck als Objekt im buffer mit ab

Geschätzer Arbeitsaufwand: 14 Tage
Realer Zeitaufwand: 21 Tage

**Comment by ReneHerthel** [comment]
@thismath Was ist ein "TIME CODE MSG PUCK", bzw. was soll es beinhalten/machen ?
Seriell-Stub?

**Comment by thismath** [comment]
Also:
TIME - Timestamp (vom Start aus)
CODE - ???
MSG - Die gesendete/empfangene Nachricht
PUCK- das Puckobjekt, welches die Nachricht erhalten hat
als struct, welches im Ringbuffer von dem Recorder gespeichert werden soll
der Seriell-Stub ist ehr für @Siltyx interessant, passte aber zum Thema Recorder, weil wir das in diesem Zusammenhang besprochen hatten.
Können wir Mittwoch nochmal drüber sprechen.

**Comment by ReneHerthel** [comment]
@thismath Alles klar, danke.

**Comment by ReneHerthel** [comment]
Es muss jetzt im gesamten System getestet werden.
